
spring:
  profiles:
    active: dev


mybatis:
  mapper-locations:
  - classpath:dao/*.xml
  - classpath*:com/**/mapper/*.xml



#redis:
#  key:
#    prefix:
#      authCode: "protal:authCode:"
#      orderId: "protal:orderId:"
#    expire:
#      authCode: 90


server:
  port: 2001

