spring:
  profiles:
    active: dev #默认为开发环境

server:
  port: 3001

mybatis:
  mapper-locations:
  - classpath:dao/*.xml
  - classpath*:com/**/mapper/*.xml

logging:
  level:
    root: info
    com.macro.mall: debug
